### ISSUE TITLE
https://pcc-assets.accusoft.com/ has a bad SSL certificate

### ISSUE THREAD

**Issue by hungrypipo** [Accusoft/prizmdoc-viewer-node-example#2]
https://pcc-assets.accusoft.com which is the domain that viewer.js and other PrizmDoc js files are referenced from in this repository has an invalid SSL.

This is the output of the issue in Firefox:

pcc-assets.accusoft.com uses an invalid security certificate. The certificate is only valid for the following names: *.s3.amazonaws.com, s3.amazonaws.com Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by mhansen-accusoft** [comment]
It looks like the URL to pull the assets for our viewer was set to allow both https and http which was unintentional.   A fix has been pushed to force the viewer assets to use http which should resolve the issue.  

Lines 12 and 13 of this file have been updated if you want to make those changes locally in your code:

https://github.com/Accusoft/prizmdoc-viewer-node-example/blob/master/views/viewFile.handlebars

**Comment by hungrypipo** [comment]
Does solve the issue of the bad SSL cert but creates another issue.
With this change the app can't be used in HTTPS because Chrome complains:
![image](https://user-images.githubusercontent.com/12138640/27656063-aa96f5d2-5c15-11e7-9378-28579c212cd3.png)

It has an issue with the two .js files being pulled from a non-secure location in a secure site.

The only way to get around this Chrome issue is to run the app in HTTP but now you're not secure and streaming documents, not good.

**Comment by hungrypipo** [comment]
The updated SSL cert on the domain hosting the viewer fixes this issue
